# Generated by Django 2.2.7 on 2019-11-06 01:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Image_test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('statut', models.BooleanField(default=True)),
                ('image', models.ImageField(upload_to='images')),
            ],
            options={
                'verbose_name': 'Image_test',
                'verbose_name_plural': 'Image_tests',
            },
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('statut', models.BooleanField(default=True)),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('statut', models.BooleanField(default=True)),
                ('description', models.TextField()),
                ('contenu', tinymce.models.HTMLField(verbose_name='content')),
                ('image_question', models.ManyToManyField(to='quizapp.Image_test')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='quizapp.Level')),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('statut', models.BooleanField(default=True)),
                ('titre', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('max_question', models.PositiveIntegerField()),
                ('correction', models.BooleanField(default=False)),
                ('single_tentative', models.BooleanField(default=True)),
                ('result_tentative', models.BooleanField()),
                ('pourcentage_requis', models.SmallIntegerField()),
                ('success_text', models.TextField()),
                ('fail_text', models.TextField()),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_levels', to='quizapp.Level')),
            ],
            options={
                'verbose_name': 'Quiz',
                'verbose_name_plural': 'Quizs',
            },
        ),
        migrations.CreateModel(
            name='Resultat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('statut', models.BooleanField(default=True)),
                ('quiz_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_resultat', to='quizapp.Quiz')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Reponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('statut', models.BooleanField(default=True)),
                ('description', models.TextField()),
                ('reponse', models.CharField(max_length=200)),
                ('score', models.IntegerField(default=True)),
                ('image_reponse', models.ManyToManyField(to='quizapp.Image_test')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_reponse', to='quizapp.Question')),
            ],
            options={
                'verbose_name': 'Reponse',
                'verbose_name_plural': 'Reponses',
            },
        ),
        migrations.AddField(
            model_name='question',
            name='quiz',
            field=models.ManyToManyField(related_name='quizs', to='quizapp.Quiz'),
        ),
    ]
