# Generated by Django 2.2.6 on 2019-11-09 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='image'),
        ),
    ]
