# Generated by Django 2.2.6 on 2019-11-11 00:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0002_level_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proposition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('statut', models.BooleanField(default=True)),
                ('propsition1', models.CharField(max_length=200)),
                ('propsition2', models.CharField(max_length=200)),
                ('propsition3', models.CharField(max_length=200)),
                ('propsition5', models.CharField(max_length=200)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposition_question', to='quizapp.Question')),
            ],
            options={
                'verbose_name': 'Proposition',
                'verbose_name_plural': 'Propositions',
            },
        ),
    ]
