# Generated by Django 2.2.7 on 2019-11-16 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0003_proposition'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='point',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='resultat',
            name='note',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='resultat',
            name='taux',
            field=models.SmallIntegerField(default=0),
        ),
    ]
