# Generated by Django 2.2.7 on 2019-11-06 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FirstSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('statut', models.BooleanField(default=True)),
                ('titre', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'FirstSection',
                'verbose_name_plural': 'FirstSections',
            },
        ),
        migrations.CreateModel(
            name='FirstSectionIndex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('statut', models.BooleanField(default=True)),
                ('image', models.ImageField(upload_to='first_section')),
                ('titre', models.CharField(max_length=50)),
                ('action', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'FirstSection',
                'verbose_name_plural': 'FirstSections',
            },
        ),
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('statut', models.BooleanField(default=True)),
                ('titre', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Newsletter',
                'verbose_name_plural': 'Newsletters',
            },
        ),
        migrations.CreateModel(
            name='SecondSectionIndex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('statut', models.BooleanField(default=True)),
                ('image', models.ImageField(upload_to='first_section')),
                ('titre', models.CharField(max_length=50)),
                ('action', models.CharField(max_length=50)),
                ('nom_cours', models.CharField(max_length=50)),
                ('nombre_cours', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'SecondSectionIndex',
                'verbose_name_plural': 'SecondSectionIndexs',
            },
        ),
    ]
