# Generated by Django 2.2.7 on 2019-11-15 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='secondsectionindex',
            old_name='nom_cours',
            new_name='nom_cours1',
        ),
        migrations.RenameField(
            model_name='secondsectionindex',
            old_name='nombre_cours',
            new_name='nombre_cours1',
        ),
        migrations.RemoveField(
            model_name='secondsectionindex',
            name='image',
        ),
        migrations.AddField(
            model_name='secondsectionindex',
            name='nom_cours2',
            field=models.CharField(default='Nom', max_length=50),
        ),
        migrations.AddField(
            model_name='secondsectionindex',
            name='nom_cours3',
            field=models.CharField(default='Nom', max_length=50),
        ),
        migrations.AddField(
            model_name='secondsectionindex',
            name='nombre_cour2',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='secondsectionindex',
            name='nombre_cours3',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
