# Generated by Django 2.2.7 on 2019-11-15 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configapp', '0002_auto_20191115_0955'),
    ]

    operations = [
        migrations.AddField(
            model_name='secondsectionindex',
            name='description',
            field=models.CharField(default='description', max_length=500),
        ),
    ]
